name: Lint
on:
  push:
    branches:
      - master
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Lint
        uses: Krizzu/eslint-check-action@v1.1.0
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          eslintFiles: "src"
          eslintConfig: ".eslintrc.js"
          eslintExt: "ts, tsx"
